=== KoBionic/node-config-server/schemas/config_schema_v1.0.json
{
  "$id": "config_schema_v1.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "$schema": {
      "default": "https://raw.githubusercontent.com/KoBionic/node-config-server/master/schemas/config_schema_v1.0.json",
      "description": "JSON schema used to validate configuration.",
      "type": "string"
    },
    "baseDirectory": {
      "default": "./config",
      "description": "Server base directory used for serving configuration files.",
      "type": [
        "null",
        "string"
      ]
    },
    "eureka": {
      "additionalProperties": false,
      "description": "Eureka services registry client configuration.",
      "items": [
        {
          "default": false,
          "type": "boolean"
        },
        {
          "additionalProperties": false,
          "properties": {
            "registry": {
              "additionalProperties": false,
              "description": "Service registry configuration.",
              "properties": {
                "host": {
                  "default": "localhost",
                  "description": "Service registry hostname.",
                  "type": "string"
                },
                "port": {
                  "default": 8761,
                  "description": "Service registry port number.",
                  "type": "integer"
                }
              },
              "type": "object"
            }
          },
          "type": "object"
        }
      ],
      "maxItems": 2,
      "minItems": 2,
      "type": [
        "array",
        "null"
      ]
    },
    "logging": {
      "additionalProperties": false,
      "description": "Logger configuration.",
      "items": [
        {
          "default": true,
          "type": "boolean"
        },
        {
          "additionalProperties": false,
          "properties": {
            "correlationId": {
              "default": true,
              "description": "Set to true to add correlation ID to the logging output.",
              "type": "boolean"
            },
            "directory": {
              "default": "./logs",
              "description": "Logs directory.",
              "type": "string"
            },
            "enableWebsocket": {
              "default": false,
              "description": "Set to true to add WebSocket logging transport.",
              "type": "boolean"
            },
            "level": {
              "default": "info",
              "description": "Logging level.",
              "enum": [
                "debug",
                "error",
                "info",
                "warn"
              ],
              "type": "string"
            },
            "name": {
              "default": "node-config-server",
              "description": "Log files basename.",
              "type": "string"
            }
          },
          "type": "object"
        }
      ],
      "maxItems": 2,
      "minItems": 2,
      "type": [
        "array",
        "null"
      ]
    },
    "security": {
      "additionalProperties": false,
      "description": "Node Config Server security configuration attributes.",
      "properties": {
        "enableCors": {
          "default": true,
          "description": "Enforce Cross-Origin Resource Sharing policy.",
          "type": "boolean"
        },
        "httpHeaders": {
          "description": "HTTP headers configuration. See https://helmetjs.github.io",
          "items": [
            {
              "default": true,
              "type": "boolean"
            },
            {
              "additionalProperties": false,
              "properties": {
                "dnsPrefetchControl": {
                  "default": true,
                  "description": "Add DNS Prefetch Control header. See https://helmetjs.github.io/docs/dns-prefetch-control",
                  "type": "boolean"
                },
                "hidePoweredBy": {
                  "default": true,
                  "description": "Add Powered-By header. See https://helmetjs.github.io/docs/hide-powered-by",
                  "type": "boolean"
                },
                "hsts": {
                  "additionalProperties": false,
                  "default": true,
                  "description": "HTTP Strict-Transport-Security configuration. See https://helmetjs.github.io/docs/hsts",
                  "properties": {
                    "includeSubDomains": {
                      "default": false,
                      "description": "If this optional parameter is specified, this rule applies to all of the site's subdomains as well.",
                      "type": "boolean"
                    },
                    "maxAge": {
                      "default": 5184000,
                      "description": "The time in seconds that the browser should remember that a site is only to be accessed using HTTPS.",
                      "type": "integer"
                    }
                  },
                  "type": [
                    "object",
                    "null"
                  ]
                },
                "ieNoOpen": {
                  "default": true,
                  "description": "Add X-Download-Options header. See https://helmetjs.github.io/docs/ienoopen/",
                  "type": "boolean"
                },
                "noSniff": {
                  "default": true,
                  "description": "Set X-Content-Type-Options header to nosniff. See https://helmetjs.github.io/docs/dont-sniff-mimetype",
                  "type": "boolean"
                },
                "xssFilter": {
                  "default": true,
                  "description": "Add X-XSS-Protection header. See https://helmetjs.github.io/docs/xss-filter",
                  "type": "boolean"
                }
              }
            }
          ],
          "type": [
            "array",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "server": {
      "additionalProperties": false,
      "description": "Node Config Server configuration attributes.",
      "properties": {
        "port": {
          "default": 20490,
          "description": "Node Config Server port number.",
          "type": "integer"
        },
        "scheme": {
          "default": "http",
          "description": "Node Config Server HTTP protocol.",
          "type": "string"
        }
      },
      "type": [
        "object",
        "null"
      ]
    }
  },
  "properties": {
    "$schema": {
      "$ref": "#/definitions/$schema"
    },
    "baseDirectory": {
      "$ref": "#/definitions/baseDirectory"
    },
    "eureka": {
      "$ref": "#/definitions/eureka"
    },
    "logging": {
      "$ref": "#/definitions/logging"
    },
    "security": {
      "$ref": "#/definitions/security"
    },
    "server": {
      "$ref": "#/definitions/server"
    }
  },
  "type": "object"
}

=== KoBionic/node-config-server/src/services/config/default.config.json
{
  "$schema": "https://raw.githubusercontent.com/KoBionic/node-config-server/master/schemas/config_schema_v1.0.json",
  "baseDirectory": "./config",
  "server": {
    "port": 20490
  },
  "eureka": [
    true,
    {
      "registry": {
        "host": "localhost",
        "port": 8761
      }
    }
  ],
  "logging": [
    true,
    {
      "correlationId": true,
      "directory": "./logs",
      "enableWebsocket": true,
      "level": "info",
      "name": "node-config-server"
    }
  ],
  "security": {
    "enableCors": true,
    "httpHeaders": [
      true,
      {
        "dnsPrefetchControl": true,
        "hidePoweredBy": true,
        "hsts": {
          "maxAge": 5184000,
          "includeSubDomains": false
        },
        "ieNoOpen": true,
        "noSniff": true,
        "xssFilter": true
      }
    ]
  }
}

=== KoBionic/node-config-server/src/services/configuration/default.config.json
{
  "$schema": "https://raw.githubusercontent.com/KoBionic/node-config-server/master/schemas/config_schema_v1.0.json",
  "baseDirectory": "./config",
  "server": {
    "port": 20490,
    "scheme": "http"
  },
  "eureka": [
    false,
    {
      "registry": {
        "host": "localhost",
        "port": 8761
      }
    }
  ],
  "logging": [
    true,
    {
      "correlationId": false,
      "directory": "./logs",
      "enableWebsocket": false,
      "level": "info",
      "name": "node-config-server"
    }
  ],
  "security": {
    "enableCors": false,
    "httpHeaders": [
      true,
      {
        "dnsPrefetchControl": true,
        "hidePoweredBy": true,
        "hsts": {
          "maxAge": 5184000,
          "includeSubDomains": false
        },
        "ieNoOpen": true,
        "noSniff": true,
        "xssFilter": true
      }
    ]
  }
}
